const actions = {
  BOARD_TASK_UPDATE_BEGIN: 'BOARD_TASK_UPDATE_BEGIN',
  BOARD_TASK_UPDATE_SUCCESS: 'BOARD_TASK_UPDATE_SUCCESS',
  BOARD_TASK_UPDATE_ERR: 'BOARD_TASK_UPDATE_ERR',
};

export default actions;
